### ISSUE TITLE
define 3 areas of interest for study

### ISSUE THREAD

**Issue by rchang0501** [WAT-ai/wildfire#24]
based on heat map: https://uwaterloo.maps.arcgis.com/apps/mapviewer/index.html?webmap=9e1fb7b8dd2446ad8bcd5affc5c58b8c

- [x] identify 3 areas of interest 
- [x] provide longitude-latitude coordinate for a rectangle that overlays on top of areas of interest

**Comment by paigekobz** [comment]
Three regions defined in Doc:

[https://docs.google.com/document/d/1DmUUEMWpzQqkv_tFX6DDlnmcbEAgZbqKGw6wv8MSo98/edit?usp=sharing](url)
